sudo: required
services:
 - docker
 
before_install:
 - docker build -t rs871997/docker-pratice -f Dockerfile.dev .
 
script:
 - docker run -e CI=true rs871997/docker-pratice npm run test -- --coverage
 
deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "Docker"
 env: "Docker-env"
 bucket: "elasticbeanstalk-us-east-2-359176990854"
 bucket_path: "Docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"